version: "3.8"

volumes:
  shared_database:
    driver: local

services:
  main:
    build:
      context: ./src/main/docker
      dockerfile: Dockerfile
    networks:
      - frontend
    ports:
      - 80:8080
      - 443:8080
    restart: always

networks:
  frontend:
  backend:
